version: '3.8'

services:
  # Solo la aplicación FastAPI
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedium-api
    restart: unless-stopped
    environment:
      # Application
      APP_NAME: "Schedium API"
      APP_VERSION: "1.0.0"
      APP_ENV: ${APP_ENV:-development}
      DEBUG: ${DEBUG:-false}
      
      # Database (externo)
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      
      # Redis (opcional, si no tienes Redis externo, comentar esta línea)
      REDIS_URL: ${REDIS_URL:-redis://localhost:6379/0}
      
      # Security
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      
      # CORS
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS:-http://localhost:3000}
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_FORMAT: ${LOG_FORMAT:-json}
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    # Usar red host para conectar a MySQL local
    network_mode: "host"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s